repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-added-large-files
      - id: check-builtin-literals
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: debug-statements
      - id: check-toml
      - id: debug-statements
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: pretty-format-json
        args:
          - --autofix
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pycqa/bandit
    rev: 1.7.3
    hooks:
      - id: bandit
        exclude: |
          (?x)(
              ^app_init/|
              ^docs/|
              ^tcex/testing/|
              ^tests/
          )
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        exclude: |
          (?x)(
              ^app_init/
          )
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        args:
          - --ignore=D104,D202,D203,D213,D300,D301,D400,D402,D406,D407,D413,D415
        exclude: |
          (?x)(
              ^docs/|
              ^tcex/threat_intelligence/|
              ^tests/
          )
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
      - id: pyupgrade
        args:
          - --py3-plus
          - --py36-plus
  - repo: https://github.com/yunojuno/pre-commit-xenon
    rev: v0.1
    hooks:
      - id: xenon
        args: ["--max-average=B", "-e=tests*"]
  - repo: local
    hooks:
      - id: pylint
        entry: pylint
        language: system
        name: pylint
        types: [python]
        args: ["--jobs=0"]
