[tool.black]
line-length = 100
skip-string-normalization = true

[tool.pydocstyle]
ignore = [
  "D202", # no blank lines allowed after function docstring
  "D203", # 1 blank line required before class docstring (found 0)
  "D213", # Multi-line docstring summary should start at the second line
  "D400", # First line should end with a period ...
  "D406", # Section name should end with a newline ...
  "D407", # Missing dashed underline after section ...
  "D413", # Missing blank line after last section ...
  "D415", # First line should end with a period, question mark, or exclamation point ...
]

[tool.pylint.messages_control]
disable = [
  "broad-exception-caught",
  "duplicate-code",
  "fixme",
  "inconsistent-return-statements", # pylint doesn't properly handle "NoReturn" in all cases
  "invalid-name",
  "logging-fstring-interpolation",
  "relative-beyond-top-level", # disable relative rule due to this project being a submodule
  "too-few-public-methods",
  "too-many-arguments",
  "too-many-branches",
  "too-many-instance-attributes",
  "too-many-locals",
  "too-many-public-methods",
  "too-many-return-statements",
]
extension-pkg-whitelist = "pydantic"
