[tool.black]
line-length = 100
skip-string-normalization = true

[tool.pylint.messages_control]
disable = [
  "broad-exception-caught",
  "fixme",
  "import-error",
  "invalid-name",
  "logging-fstring-interpolation",
  "no-name-in-module",
  "too-few-public-methods",
  "too-many-ancestors",
  "too-many-arguments",
  "too-many-instance-attributes",
  "too-many-function-args",
  "too-many-locals",
]
#   "broad-except",
#   "duplicate-code",
#   "missing-function-docstring",
#   "too-many-branches",
#   "too-many-lines",
#   "too-many-public-methods",
#   "too-many-statements",
#   "wrong-spelling-in-comment",
#   "wrong-import-order",
extension-pkg-allow-list = "falcon"
extension-pkg-whitelist = "pydantic"
ignored-classes = "scoped_session"
