[tool.black]
line-length = 100
skip-string-normalization = true

[tool.pylint.master]
init-hook = "import sys;sys.path.insert(0, 'deps')"

[tool.pylint.messages_control]
disable = [
  "broad-except",
  "duplicate-code",
  "fixme",
  "import-error",
  "invalid-name",
  "logging-fstring-interpolation",
  "missing-function-docstring",
  "too-few-public-methods",
  "too-many-ancestors",
  "too-many-arguments",
  "too-many-branches",
  "too-many-instance-attributes",
  "too-many-lines",
  "too-many-locals",
  "too-many-public-methods",
  "too-many-statements",
  "wrong-spelling-in-comment",
  "wrong-import-order",
]
extension-pkg-whitelist = "pydantic"

[tool.pytest.ini_options]
junit_family = "xunit2"
testpaths = [
  "tests",
]
